### ISSUE TITLE
 'KGRAGService' object has no attribute '_enhanced_schema'. 

### ISSUE THREAD

**Issue by HonggangLiu891117** [lukasbahr/kg-rag-fmea#2]
Hello, I'm trying to run the kg_rag.py, filled in the Neo4j and Azure information, and nothing else changed, but this error occuored:
Traceback (most recent call last):
  File "C:\Projects\kg-rag-fmea-main\kg-rag-fmea-main\code\kg_rag.py", line 614, in <module>
    rag_service = KGRAGService()
  File "C:\Projects\kg-rag-fmea-main\kg-rag-fmea-main\code\kg_rag.py", line 130, in __init__
    super().__init__(
  File "C:\Projects\kg-rag-fmea-main\kg-rag-fmea-main\code\kg_rag.py", line 123, in __init__
    self.refresh_schema()
  File "C:\Projects\kg-rag-fmea-main\venv\lib\site-packages\langchain_community\graphs\neo4j_graph.py", line 446, in refresh_schema
    if self._enhanced_schema:
AttributeError: 'KGRAGService' object has no attribute '_enhanced_schema'. Did you mean: '_enhanced_schema_cypher'?

I checked neo4j_graph.py, '_enhanced_schema_cypher' is an attribute of Neo4jGraph.
Can anyone help me how to solve this problem?

**Comment by lukasbahr** [comment]
This issue should be fixed. Please let me know otherwise.

**Comment by mipmip** [comment]
I have the same problem. Does not seem to be fixed.

**Comment by mipmip** [comment]
Using this fork to get a working version.... https://github.com/jgarciamesa/kg-rag-fmea
